name = "gestion-whatsapp-turnos"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[[d1_databases]]
binding = "DB"
database_name = "gestion-whatsapp-turnos"
database_id = "7ae0a525-6b93-48b4-95dc-1e5d596f4b6f"

[triggers]
crons = ["0 * * * *"]

[vars]
WEBHOOK_PUBLIC_URL = "https://gestion-whatsapp-turnos.walphur.workers.dev"
